<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/09 17:01:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=seminar',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
